name: GitHub Actions
on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - run: make install
      - run: make lint
